[project]
name = "orchestration-via-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.8.1",
    "openai-agents>=0.3.2",
    "python-dotenv>=1.1.1",
]
